# .github/dependabot.yml
version: 2
updates:
  # Enable Python/pip dependency updates
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    # Group all minor and patch updates together
    groups:
      minor-patch:
        update-types:
          - "minor"
          - "patch"
    # Set review requirements and limits
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "automerge"

  # Keep GitHub Actions up-to-date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "ci"
      - "dependencies"
      - "automerge"
